vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        manuals:
            uri_prefix: /docs/manuals
            upload_destination: '%kernel.project_dir%/public/docs/manuals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer